export { yvlColors, yvlColorCssVariables } from "./colors";
export { yvlTypography } from "./typography";
export { yvlSpacing } from "./spacing";
export { yvlRadii } from "./radii";
export { yvlMotion } from "./motion";
import { yvlColors } from "./colors";
import { yvlTypography } from "./typography";
import { yvlSpacing } from "./spacing";
import { yvlRadii } from "./radii";
import { yvlMotion } from "./motion";
export const yvlVersion = "1.0.0" as const;
export const yvlTokens = {color:yvlColors,typography:yvlTypography,spacing:yvlSpacing,radii:yvlRadii,motion:yvlMotion} as const;
