"use client";

import { FormEvent, ReactNode, useMemo, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, CalendarDays, CircleDollarSign, Filter, Pencil, Plus, Search, Trash2, Wallet, X } from "lucide-react";
import type { Client, FinanceStatus, FinanceTransaction, FinanceTransactionInput, FinanceTransactionType, Project } from "@/lib/types";
import { useLanguage } from "@/components/i18n/language-provider";

export function FinanceView({ items, projects, clients, onCreate, onEdit, onDelete }: { items: FinanceTransaction[]; projects: Project[]; clients: Client[]; onCreate: () => void; onEdit: (item: FinanceTransaction) => void; onDelete: (item: FinanceTransaction) => void }) {
  const { locale, text } = useLanguage();
  const typeLabel: Record<FinanceTransactionType, string> = { Income: text("دخل", "Income"), Expense: text("مصروف", "Expense") };
  const statusLabel: Record<FinanceStatus, string> = { Pending: text("معلّق", "Pending"), Paid: text("مدفوع", "Paid"), Cancelled: text("ملغي", "Cancelled") };
  const formatMoney = (value: number, currency = "SAR") => new Intl.NumberFormat(locale === "ar" ? "ar-SA" : "en-US", { style: "currency", currency, maximumFractionDigits: 2 }).format(value);
  const monthFormatter = useMemo(() => new Intl.DateTimeFormat(locale === "ar" ? "ar-SA" : "en-US", { month: "short" }), [locale]);
  const dateFormatter = useMemo(() => new Intl.DateTimeFormat(locale === "ar" ? "ar-SA" : "en-US", { day: "numeric", month: "short", year: "numeric" }), [locale]);
  const [q, setQ] = useState("");
  const [type, setType] = useState<"All" | FinanceTransactionType>("All");

  const visible = useMemo(() => items.filter((item) => (type === "All" || item.type === type) && (!q || [item.description, item.category, item.notes].some((value) => (value ?? "").toLowerCase().includes(q.toLowerCase())))), [items, q, type]);
  const primaryCurrency = useMemo(() => { const counts = new Map<string, number>(); items.forEach((item) => counts.set(item.currency, (counts.get(item.currency) ?? 0) + 1)); if (counts.has("SAR")) return "SAR"; return [...counts.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? "SAR"; }, [items]);
  const currencies = useMemo(() => [...new Set(items.map((item) => item.currency))], [items]);
  const primaryPaid = items.filter((item) => item.status === "Paid" && item.currency === primaryCurrency);
  const income = primaryPaid.filter((item) => item.type === "Income").reduce((sum, item) => sum + Number(item.amount), 0);
  const expense = primaryPaid.filter((item) => item.type === "Expense").reduce((sum, item) => sum + Number(item.amount), 0);
  const monthly = useMemo(() => { const now = new Date(); return Array.from({ length: 6 }, (_, index) => { const date = new Date(now.getFullYear(), now.getMonth() - (5 - index), 1); const month = date.getMonth(); const year = date.getFullYear(); const monthItems = items.filter((item) => { const itemDate = new Date(item.transaction_date); return item.status === "Paid" && item.currency === primaryCurrency && itemDate.getMonth() === month && itemDate.getFullYear() === year; }); return { label: monthFormatter.format(date), income: monthItems.filter((item) => item.type === "Income").reduce((sum, item) => sum + Number(item.amount), 0), expense: monthItems.filter((item) => item.type === "Expense").reduce((sum, item) => sum + Number(item.amount), 0) }; }); }, [items, primaryCurrency, monthFormatter]);
  const maxMonthly = Math.max(1, ...monthly.flatMap((month) => [month.income, month.expense]));
  const recent = [...items].sort((a, b) => b.transaction_date.localeCompare(a.transaction_date)).slice(0, 5);
  const categoryTotals = useMemo(() => { const totals = new Map<string, number>(); primaryPaid.filter((item) => item.type === "Expense").forEach((item) => totals.set(item.category, (totals.get(item.category) ?? 0) + Number(item.amount))); return [...totals.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5); }, [items, primaryCurrency]);
  const maxCategory = Math.max(1, ...categoryTotals.map(([, amount]) => amount));
  const metricValue = (value: number) => (items.length ? formatMoney(value, primaryCurrency) : "—");

  return <section className="finance-panel">
    <div className="finance-summary">
      <FinanceMetric icon={<ArrowUpRight />} label={text("إجمالي الدخل", "Total income")} value={metricValue(income)} tone="income" />
      <FinanceMetric icon={<ArrowDownLeft />} label={text("إجمالي المصروفات", "Total expenses")} value={metricValue(expense)} tone="expense" />
      <FinanceMetric icon={<Wallet />} label={text("صافي التدفق", "Net flow")} value={metricValue(income - expense)} tone={income - expense >= 0 ? "income" : "expense"} />
      <FinanceMetric icon={<CircleDollarSign />} label={text("المعاملات", "Transactions")} value={items.length ? String(items.length) : "—"} tone="neutral" />
    </div>
    {currencies.length > 1 && <p className="finance-currency-note">{text(`المؤشرات محسوبة بعملة ${primaryCurrency} فقط. توجد معاملات إضافية بعملات: ${currencies.filter((currency) => currency !== primaryCurrency).join("، ")}.`, `Metrics are calculated in ${primaryCurrency} only. Additional transactions exist in: ${currencies.filter((currency) => currency !== primaryCurrency).join(", ")}.`)}</p>}
    <div className="finance-toolbar"><label className="search-box"><Search size={17} /><input value={q} onChange={(event) => setQ(event.target.value)} placeholder={text("ابحث في الوصف أو التصنيف…", "Search description or category…")} /></label><label className="finance-filter"><Filter size={16} /><select value={type} onChange={(event) => setType(event.target.value as typeof type)}><option value="All">{text("كل المعاملات", "All transactions")}</option><option value="Income">{text("الدخل", "Income")}</option><option value="Expense">{text("المصروفات", "Expenses")}</option></select></label></div>

    {items.length > 0 && <div className="finance-insights-grid">
      <article className="finance-insight finance-chart-card"><header><div><span className="section-kicker">CASH FLOW</span><h2>{text("الدخل والمصروفات", "Income and expenses")}</h2></div><small>{text("آخر 6 أشهر", "Last 6 months")} · {primaryCurrency}</small></header><div className="finance-chart" aria-label={text("مقارنة الدخل والمصروفات خلال آخر ستة أشهر", "Income and expense comparison over the last six months")}>{monthly.map((month) => <div className="finance-chart-month" key={month.label}><div className="finance-bars"><i className="income-bar" style={{ height: `${Math.max(month.income ? 8 : 0, (month.income / maxMonthly) * 100)}%` }} title={`${text("دخل", "Income")}: ${formatMoney(month.income, primaryCurrency)}`} /><i className="expense-bar" style={{ height: `${Math.max(month.expense ? 8 : 0, (month.expense / maxMonthly) * 100)}%` }} title={`${text("مصروف", "Expense")}: ${formatMoney(month.expense, primaryCurrency)}`} /></div><span>{month.label}</span></div>)}</div><footer className="finance-chart-legend"><span><i className="income-dot" /> {text("الدخل", "Income")}</span><span><i className="expense-dot" /> {text("المصروفات", "Expenses")}</span></footer></article>
      <article className="finance-insight"><header><div><span className="section-kicker">EXPENSES</span><h2>{text("أعلى التصنيفات إنفاقًا", "Top spending categories")}</h2></div></header>{categoryTotals.length ? <div className="finance-categories">{categoryTotals.map(([category, amount]) => <div className="finance-category" key={category}><div><b>{category}</b><span>{formatMoney(amount, primaryCurrency)}</span></div><em><i style={{ width: `${(amount / maxCategory) * 100}%` }} /></em></div>)}</div> : <div className="mini-empty">{text("لا توجد مصروفات مدفوعة بعد.", "No paid expenses yet.")}</div>}</article>
    </div>}

    {visible.length ? <div className="finance-table-section"><div className="finance-section-title"><div><span className="section-kicker">TRANSACTIONS</span><h2>{q || type !== "All" ? text("نتائج البحث", "Search results") : text("آخر المعاملات", "Recent transactions")}</h2></div><small>{text(`${visible.length} معاملة`, `${visible.length} transaction(s)`)}</small></div><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>{text("التاريخ", "Date")}</th><th>{text("النوع", "Type")}</th><th>{text("الوصف", "Description")}</th><th>{text("الارتباط", "Linked to")}</th><th>{text("الحالة", "Status")}</th><th>{text("المبلغ", "Amount")}</th><th /></tr></thead><tbody>{(q || type !== "All" ? visible : recent).map((item) => <tr key={item.id}><td><span className="date-cell"><CalendarDays size={14} />{dateFormatter.format(new Date(item.transaction_date))}</span></td><td><span className={`finance-type ${item.type.toLowerCase()}`}>{item.type === "Income" ? <ArrowUpRight size={14} /> : <ArrowDownLeft size={14} />} {typeLabel[item.type]}</span></td><td><b>{item.description}</b><small>{item.category}</small></td><td>{projects.find((project) => project.id === item.project_id)?.name || clients.find((client) => client.id === item.client_id)?.name || "—"}</td><td><span className={`finance-status ${item.status.toLowerCase()}`}>{statusLabel[item.status]}</span></td><td className={item.type === "Income" ? "amount-income" : "amount-expense"}>{item.type === "Income" ? "+" : "-"}{formatMoney(Number(item.amount), item.currency)}</td><td><div className="table-actions"><button onClick={() => onEdit(item)} aria-label={text("تعديل", "Edit")}><Pencil size={14} /></button><button className="danger" onClick={() => onDelete(item)} aria-label={text("حذف", "Delete")}><Trash2 size={14} /></button></div></td></tr>)}</tbody></table></div></div> : <div className="empty-state finance-empty"><span><Wallet /></span><h3>{items.length ? text("لا توجد نتائج مطابقة.", "No matching results.") : text("ابدأ تسجيل حركة أعمالك المالية.", "Start recording your financial activity.")}</h3><p>{items.length ? text("جرّب تغيير البحث أو عامل التصفية.", "Try changing the search or filter.") : text("أضف أول دخل أو مصروف لتحصل على مؤشرات وتقارير مفيدة هنا.", "Add your first income or expense to unlock useful metrics and reports here.")}</p>{!items.length && <button className="primary compact" onClick={onCreate}><Plus size={16} /> {text("أضف أول معاملة", "Add first transaction")}</button>}</div>}
  </section>;
}

function FinanceMetric({ icon, label, value, tone }: { icon: ReactNode; label: string; value: string; tone: string }) { return <article className={`finance-metric ${tone}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article>; }

export function FinanceModal({ item, projects, clients, onClose, onSave }: { item: FinanceTransaction | null; projects: Project[]; clients: Client[]; onClose: () => void; onSave: (input: FinanceTransactionInput, current?: FinanceTransaction) => Promise<boolean> }) {
  const { text } = useLanguage();
  const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); const input: FinanceTransactionInput = { type: String(form.get("type")) as FinanceTransactionType, category: String(form.get("category") || "General").trim(), description: String(form.get("description") || "").trim(), amount: Number(form.get("amount") || 0), currency: String(form.get("currency") || "SAR").toUpperCase(), status: String(form.get("status")) as FinanceStatus, transaction_date: String(form.get("transaction_date")), project_id: String(form.get("project_id") || "") || null, client_id: String(form.get("client_id") || "") || null, notes: String(form.get("notes") || "").trim() || null }; if (!await onSave(input, item ?? undefined)) setSaving(false); }
  return <div className="modal-backdrop"><div className="project-modal"><div className="modal-head"><div><span className="section-kicker">FINANCE</span><h2>{item ? text("تعديل المعاملة", "Edit transaction") : text("معاملة مالية جديدة", "New financial transaction")}</h2></div><button className="icon-button" onClick={onClose} aria-label={text("إغلاق", "Close")}><X size={20} /></button></div><form className="project-form" onSubmit={submit}>
    <label><span>{text("النوع", "Type")}</span><select name="type" defaultValue={item?.type || "Expense"}><option value="Income">{text("دخل", "Income")}</option><option value="Expense">{text("مصروف", "Expense")}</option></select></label>
    <label><span>{text("الحالة", "Status")}</span><select name="status" defaultValue={item?.status || "Paid"}><option value="Paid">{text("مدفوع", "Paid")}</option><option value="Pending">{text("معلّق", "Pending")}</option><option value="Cancelled">{text("ملغي", "Cancelled")}</option></select></label>
    <label className="full"><span>{text("الوصف *", "Description *")}</span><input name="description" required defaultValue={item?.description || ""} /></label><label><span>{text("التصنيف *", "Category *")}</span><input name="category" required defaultValue={item?.category || "General"} /></label><label><span>{text("التاريخ *", "Date *")}</span><input type="date" name="transaction_date" required defaultValue={item?.transaction_date || new Date().toISOString().slice(0, 10)} /></label><label><span>{text("المبلغ *", "Amount *")}</span><input type="number" min="0" step="0.01" name="amount" required defaultValue={item?.amount ?? 0} /></label><label><span>{text("العملة", "Currency")}</span><input name="currency" maxLength={3} defaultValue={item?.currency || "SAR"} /></label>
    <label><span>{text("المشروع", "Project")}</span><select name="project_id" defaultValue={item?.project_id || ""}><option value="">{text("بدون مشروع", "No project")}</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label><label><span>{text("العميل", "Client")}</span><select name="client_id" defaultValue={item?.client_id || ""}><option value="">{text("بدون عميل", "No client")}</option>{clients.map((client) => <option value={client.id} key={client.id}>{client.name}</option>)}</select></label><label className="full"><span>{text("ملاحظات", "Notes")}</span><textarea name="notes" rows={4} defaultValue={item?.notes || ""} /></label><div className="form-actions full"><button type="button" onClick={onClose}>{text("إلغاء", "Cancel")}</button><button className="primary" disabled={saving}>{saving ? text("جارٍ الحفظ…", "Saving…") : text("حفظ", "Save")}</button></div>
  </form></div></div>;
}
